### ISSUE TITLE
Spigot timings

### ISSUE THREAD

**Issue by Talfereg** [JamesPeters98/ChestsPlusPlus#10]
My server has been having a lot of lag since we updated to 1.16.1 so I ran some tests and I'm not sure if this is normal or not, but it's the only plugin being used while nobody is online and it looks like a high %, not sure.

https://imgur.com/a/PYyZd4s

If this is normal, just let me know. I'll have to mess around with some other settings.

Thanks

**Comment by JamesPeters98** [comment]
Hmm, that does look like abnormally high usage, how many people are on the server, and how many ChestLinks and Hoppers are you using?

I have noticed some performance issue with that method, mostly that unloaded chunks are still being run, and also inventories being sorted when nobody was viewing the inventory - I think this may be the largest cause of lag but I will do some tests myself now!

**Comment by JamesPeters98** [comment]
Also, if you would like me to take a more detailed look you could email me (email@jamesdpeters.com) a zip file of your server and I could take a look at the timings/lag myself!

**Comment by Talfereg** [comment]
Hey, so we fixed the lag issue. Most of it was switching over to Paper instead of Spigot. However, Chests++ is still quite high but it doesn't seem to be effecting anything. We aren't getting the "server can't keep up" messages anymore and everyone says it seems to be almost no lag anymore.  I am now using the most recent beta version of Chests++  1.5 beta 3

Here is a timing report after 3 minutes with 2 people online:
https://timings.aikar.co/?id=45b8a01bc788496bad8d888d20ad1f4d

Stills seems high, but it doesn't appear to be affecting anyone. Mostly I might have 10 people on at a time. I imagine there are 50 locked chests at least.

**Comment by Talfereg** [comment]
I'll try the Update VirtualChestToHopper.java fix when my players are offline.

**Comment by JamesPeters98** [comment]
Okay cool!

I have made some performance improvements and still have some more that I possibly could add, they aren't in that Beta you are running.

I will be pushing a new Beta soon though with those fixes in.

**Comment by JamesPeters98** [comment]
> I'll try the Update VirtualChestToHopper.java fix when my players are offline.

That fix isn't out just yet! :)

**Comment by Talfereg** [comment]
> > I'll try the Update VirtualChestToHopper.java fix when my players are offline.
> 
> That fix isn't out just yet! :)

Oh I thought I could just copy the file into the jar file to replace the old one. I shall wait. 

In your fix, if the chests unload while the chunk isn't being used, does the chunk just reload if the player opens a chest that is connected to a chest in an un-loaded chunk? I think you know what I'm saying lol

**Comment by JamesPeters98** [comment]
> > > I'll try the Update VirtualChestToHopper.java fix when my players are offline.
> > 
> > 
> > That fix isn't out just yet! :)
> 
> Oh I thought I could just copy the file into the jar file to replace the old one. I shall wait.
> 
> In your fix, if the chests unload while the chunk isn't being used, does the chunk just reload if the player opens a chest that is connected to a chest in an un-loaded chunk? I think you know what I'm saying lol

Well, considering that other hoppers stop working in unloaded chunks I currently make it so that virtual hoppers in unloaded chunks stop too. I may add it as an option in the config so that you can enable that behaviour on/off.

**Comment by Talfereg** [comment]
Okay cool. Thanks for your help.

**Comment by JamesPeters98** [comment]
Hey, you might want to try out the latest BETA and see if this has any improvements for you! https://github.com/JamesPeters98/ChestsPlusPlus/releases/tag/v1.5-BETA-4

**Comment by Talfereg** [comment]
Thanks, I'll try to get it installed today or tomorrow

**Comment by JamesPeters98** [comment]
> Thanks, I'll try to get it installed today or tomorrow

Just found out there is a bug that only allows the current Beta to run on 1.16. I'm fixing it now, also if you try a beta make sure you backup your chests.yml file. This beta performs an upgrade to the storage system, and moves the file to /plugins/ChestsPlusPlus/data/storage.yml

**Comment by Talfereg** [comment]
Okay thanks for the heads up

**Comment by Talfereg** [comment]
So I upgraded to Beta 4 - not seeing the high usage anymore. I'll check again later once more players have been on. Great work!

**Comment by Talfereg** [comment]
Also, the icon on the front of the chest that shows what's in it is awesome!

**Comment by JamesPeters98** [comment]
> So I upgraded to Beta 4 - not seeing the high usage anymore. I'll check again later once more players have been on. Great work!

Sweet! Glad the fix has worked! 

> Also, the icon on the front of the chest that shows what's in it is awesome!

Looks good, doesn't it! AutoCrafting Tables show them too! Join the [Discord ](https://discord.gg/HXcZK7z) if you want more info! :)
