### ISSUE TITLE
After reboot linked chest aren't working anymore

### ISSUE THREAD

**Issue by NLLucifer** [JamesPeters98/ChestsPlusPlus#61]
After a reboot the linked chests aren't working anymore. When trying to add a new chest to the chest link group using the command i get the following error:

`[09:56:21] [Server thread/ERROR]: Exception when NL_Lucifer attempted to tab complete cl add
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/cl add ' in plugin ChestsPlusPlus v2.5.2-BETA
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.tabCompleteCommand(CraftServer.java:1947) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.tabComplete(CraftServer.java:1919) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at org.bukkit.craftbukkit.v1_18_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:3363-Spigot-f65de01-e36f759]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:598) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:712) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:29) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.network.protocol.game.PacketPlayInTabComplete.a(SourceFile:7) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:110) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1113) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.jamesdpeters.minecraft.chests.storage.chestlink.ChestLinkStorageType.getOpenableStorageList(org.bukkit.entity.Player, 
String)" because the return value of "com.jamesdpeters.minecraft.chests.serialize.Config.getChestLink()" is null
        at com.jamesdpeters.minecraft.chests.commands.ChestLinkCommand.onTabComplete(ChestLinkCommand.java:218) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 25 more`

**Comment by JamesPeters98** [comment]
Ah, yes that is a Beta bug. I'll push a new update today

**Comment by JamesPeters98** [comment]
Fixed in #5bc7fbc

**Comment by JamesPeters98** [comment]
New Beta available now: https://github.com/JamesPeters98/ChestsPlusPlus/releases/tag/v2.5.2-Beta-2

**Comment by NLLucifer** [comment]
Checked it out with the new beta, still get the following error on startup:

`[18:00:55] [Server thread/ERROR]: Error occurred while enabling ChestsPlusPlus v2.5.2-BETA-2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.jamesdpeters.minecraft.chests.NMSProvider.setItemFrameVisible(org.bukkit.entity.ItemFrame, boolean)" because the return value of "com.jamesdpeters.minecraft.chests.Api.getNmsProvider()" is null
	at com.jamesdpeters.minecraft.chests.EntityEventListener.lambda$setItemFrames$1(EntityEventListener.java:54) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.jamesdpeters.minecraft.chests.EntityEventListener.setItemFrames(EntityEventListener.java:54) ~[?:?]
	at com.jamesdpeters.minecraft.chests.EntityEventListener.setItemFrames(EntityEventListener.java:43) ~[?:?]
	at com.jamesdpeters.minecraft.chests.EntityEventListener.fixEntities(EntityEventListener.java:23) ~[?:?]
	at com.jamesdpeters.minecraft.chests.ChestsPlusPlus.lambda$onEnable$2(ChestsPlusPlus.java:130) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.jamesdpeters.minecraft.chests.ChestsPlusPlus.onEnable(ChestsPlusPlus.java:129) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3363-Spigot-f65de01-e36f759]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by JamesPeters98** [comment]
What version of MC are you running, and what server type?

**Comment by NLLucifer** [comment]
18:00:22] [Server thread/INFO]: This server is running CraftBukkit version 3363-Spigot-f65de01-e36f759 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

**Comment by JamesPeters98** [comment]
Okay, should be fixed in the next Beta.

Fixed in 332d6d3

**Comment by NLLucifer** [comment]
After installing the 3th beta, i get the following error when creating an autocrafter:

`[22:38:47] [Server thread/INFO]: NL_Lucifer issued server command: /cl add ironfarm
[22:38:47] [Craft Scheduler Thread - 0/WARN]: [ChestsPlusPlus] Plugin ChestsPlusPlus v2.5.2-BETA-3 generated an exception while executing task 253
java.lang.NullPointerException: Nodes must be provided.
        at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:30) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:30) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:134) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:190) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:30) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:321) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:30) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95) ~[snakeyaml-1.30.jar:?]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65) ~[snakeyaml-1.30.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.toNodeTree(YamlConfiguration.java:186) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:77) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.jamesdpeters.minecraft.chests.serialize.Config.save(Config.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3380-Spigot-8965a50-0ba6b90]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3380-Spigot-8965a50-0ba6b90]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by JamesPeters98** [comment]
Can you try the latest beta now?
